version: 1.0.{build}
branches:
  only:
  - develop
os: Visual Studio 2015 RC
init:
- ps: dnvm upgrade
environment:
  VisualStudioVersion: 14.0
install:
- ps: dnu restore
build:
  verbosity: minimal
test_script:
- ps: dnx test\Dice.Abstractions.Tests test